services:
  planner:
    build: .
    image: planner:latest
    container_name: planner
    ports:
      - "3000:3000"
    volumes:
      - ./data:/data
    environment:
      TZ: Europe/Amsterdam
    env_file:
      - path: .env
        required: false
    restart: unless-stopped
